export const types = {
    FETCH_SELLERS_REQUEST: 'FETCH_SELLERS_REQUEST',
    FETCH_SELLERS_FAILURE: 'FETCH_SELLERS_FAILURE',
    FETCH_SELLERS_SUCCESS: 'FETCH_SELLERS_SUCCESS',

    FETCH_SELLERS_BY_ID_REQUEST: 'FETCH_SELLERS_BY_ID_REQUEST',
    FETCH_SELLERS_BY_ID_FAILURE: 'FETCH_SELLERS_BY_ID_FAILURE',
    FETCH_SELLERS_BY_ID_SUCCESS: 'FETCH_SELLERS_BY_ID_SUCCESS',

    CREATE_SELLERS_REQUEST: 'CREATE_SELLERS_REQUEST',
    CREATE_SELLERS_FAILURE: 'CREATE_SELLERS_FAILURE',
    CREATE_SELLERS_SUCCESS: 'CREATE_SELLERS_SUCCESS',

    UPDATE_SELLERS_REQUEST: 'UPDATE_SELLERS_REQUEST',
    UPDATE_SELLERS_FAILURE: 'UPDATE_SELLERS_FAILURE',
    UPDATE_SELLERS_SUCCESS: 'UPDATE_SELLERS_SUCCESS',

    DELETE_SELLERS_REQUEST: 'DELETE_SELLERS_REQUEST',
    DELETE_SELLERS_FAILURE: 'DELETE_SELLERS_FAILURE',
    DELETE_SELLERS_SUCCESS: 'DELETE_SELLERS_SUCCESS',
}