export const types = {
    FETCH_CUSTOMERS_REQUEST: 'FETCH_CUSTOMERS_REQUEST',
    FETCH_CUSTOMERS_FAILURE: 'FETCH_CUSTOMERS_FAILURE',
    FETCH_CUSTOMERS_SUCCESS: 'FETCH_CUSTOMERS_SUCCESS',

    FETCH_CUSTOMERS_BY_ID_REQUEST: 'FETCH_CUSTOMERS_BY_ID_REQUEST',
    FETCH_CUSTOMERS_BY_ID_FAILURE: 'FETCH_CUSTOMERS_BY_ID_FAILURE',
    FETCH_CUSTOMERS_BY_ID_SUCCESS: 'FETCH_CUSTOMERS_BY_ID_SUCCESS',

    CREATE_CUSTOMERS_REQUEST: 'CREATE_CUSTOMERS_REQUEST',
    CREATE_CUSTOMERS_FAILURE: 'CREATE_CUSTOMERS_FAILURE',
    CREATE_CUSTOMERS_SUCCESS: 'CREATE_CUSTOMERS_SUCCESS',

    UPDATE_CUSTOMERS_REQUEST: 'UPDATE_CUSTOMERS_REQUEST',
    UPDATE_CUSTOMERS_FAILURE: 'UPDATE_CUSTOMERS_FAILURE',
    UPDATE_CUSTOMERS_SUCCESS: 'UPDATE_CUSTOMERS_SUCCESS',

    DELETE_CUSTOMERS_REQUEST: 'DELETE_CUSTOMERS_REQUEST',
    DELETE_CUSTOMERS_FAILURE: 'DELETE_CUSTOMERS_FAILURE',
    DELETE_CUSTOMERS_SUCCESS: 'DELETE_CUSTOMERS_SUCCESS',
}