export const types = {
    FETCH_INVOICES_REQUEST: 'FETCH_INVOICES_REQUEST',
    FETCH_INVOICES_FAILURE: 'FETCH_INVOICES_FAILURE',
    FETCH_INVOICES_SUCCESS: 'FETCH_INVOICES_SUCCESS',

    FETCH_INVOICES_BY_ID_REQUEST: 'FETCH_INVOICES_BY_ID_REQUEST',
    FETCH_INVOICES_BY_ID_FAILURE: 'FETCH_INVOICES_BY_ID_FAILURE',
    FETCH_INVOICES_BY_ID_SUCCESS: 'FETCH_INVOICES_BY_ID_SUCCESS',

    CREATE_INVOICES_REQUEST: 'CREATE_INVOICES_REQUEST',
    CREATE_INVOICES_FAILURE: 'CREATE_INVOICES_FAILURE',
    CREATE_INVOICES_SUCCESS: 'CREATE_INVOICES_SUCCESS',

    UPDATE_INVOICES_REQUEST: 'UPDATE_INVOICES_REQUEST',
    UPDATE_INVOICES_FAILURE: 'UPDATE_INVOICES_FAILURE',
    UPDATE_INVOICES_SUCCESS: 'UPDATE_INVOICES_SUCCESS',

    DELETE_INVOICES_REQUEST: 'DELETE_INVOICES_REQUEST',
    DELETE_INVOICES_FAILURE: 'DELETE_INVOICES_FAILURE',
    DELETE_INVOICES_SUCCESS: 'DELETE_INVOICES_SUCCESS',
}